### ISSUE TITLE
CSV Import: UTF-8 issue

### ISSUE THREAD

**Issue by infabo** [magedeveloper/dataviewer#11]
The CSV import module can't handle Umlaut-Characters.
No matter which file-encoding is used (utf-8 or ansi), always broken.

Mr. TÃ¤m

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 14. Mai 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 15. Mai 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Peter Ernest (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by magedeveloper** [comment]
Hey @infabo ,

could you please tell me the Version you are using?
The BackendCsvAssistantController.php had utf8 encoding twice, so it created a mess.
One of them will be removed in the next master version and is already fixed in dev-7/dev-8

**Comment by infabo** [comment]
Using 1.7.3 right now.

**Comment by magedeveloper** [comment]
Could you please switch to master-7 to get the latest 1.7.4 and see if this works.

**Comment by infabo** [comment]
master-7 works.
