### ISSUE TITLE
[Dev-8] Selection issue

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#12]
Hi,
With the latest commit on dev-8 (not the separate folder you sent me), the selection plugin doesn't work anymore : only one record is displayed in the list of selected items. I cleared my cookies but it didn't solve it.

**Comment by magedeveloper** [comment]
Hi Adrien,

quoting of the queries was incorrect.
I commited the fix

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 21. Mai 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 22. Mai 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Peter Ernest (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by adrienjacob** [comment]
Thanks !
