### ISSUE TITLE
CSV Import: Always imports to page 0

### ISSUE THREAD

**Issue by infabo** [magedeveloper/dataviewer#13]
CSV Import Assistant always imports records to pid 0, regardless of chosen target page.

Tested on master-7.

**Comment by magedeveloper** [comment]
i've tested the import several times today. could you please uninstall and directly install the extension again in the extension manager then clear all the caches?

**Comment by infabo** [comment]
I've tested it on 3 different TYPO3 instances. It imports to page with pid 0, which is not desirable and breaks list module too.

**Comment by infabo** [comment]
@magedeveloper Maybe related to MySQL 5.7.

**Comment by infabo** [comment]
@magedeveloper No, not related to MySQL 5.7. Had the same problem with YAG gallery, no matter what, a new gallery always was created on page UID 0. I already went crazy. Now I disabled the dataviewer extension - and now I can create galleries within a storage folder again.

**Comment by infabo** [comment]
@magedeveloper tracked it down. 1.2.1 was OK, the issue with pid=0 started with version 1.3.0.

**Comment by infabo** [comment]
As there are no version tags used in this repo, I can't investigate further.

**Comment by magedeveloper** [comment]
Hi @infabo,
thank you so much for your effort!
I think the last commit 6c05fbf in dev-7 could solve the problem because it adds the selected pid to the record data.

The CSV Import came with 1.3.0.

**Comment by infabo** [comment]
hi @magedeveloper,

I can confirm 6c05fbf fixed the issue. Thank you!
