### ISSUE TITLE
Conflict with extension: yag

### ISSUE THREAD

**Issue by infabo** [magedeveloper/dataviewer#14]
There seems to be a conflict with the yag gallery extension.

With dataviewer enabled/installed, it is not possible to create a new gallery record inside a particular storage folder. All new records will go to pid 0 instead.
Once you disable/uninstall dataviewer it is working fine again.

Steps to reproduce:

TYPO3 7.6.18
dataviewer dev-7
yag 4.1.2

Go to backend module "Gallery", choose a YAG storage folder and add a new gallery-record.

![grafik](https://cloud.githubusercontent.com/assets/3999104/26407366/33d37c12-409b-11e7-9084-584584459dd1.png)

![grafik](https://cloud.githubusercontent.com/assets/3999104/26407396/4dab0196-409b-11e7-8163-50d816d55756.png)

![grafik](https://cloud.githubusercontent.com/assets/3999104/26407412/5ab05e0e-409b-11e7-80f7-331c78f299f0.png)

Apparently not.

Disable dataviewer. Return to Gallery module. Once again create new gallery - et voila. Gallery there.

![grafik](https://cloud.githubusercontent.com/assets/3999104/26407496/9b87910e-409b-11e7-946d-84e9d988223f.png)

**Comment by infabo** [comment]
Forgot to mention: This is broken since dataviewer 1.3.0 (working until 1.2.1)

**Comment by magedeveloper** [comment]
That issue comes from the usage of the fieldRepository in [https://github.com/magedeveloper/dataviewer/blob/dev-7/Classes/Hooks/ExtTablesInclusion.php](url) at line 96. I am still not sure how to solve this. A different initialization of the repository doesn't lead to a result. Maybe i need to find a better hook when more extbase parts are initialized.

**Comment by infabo** [comment]
Are you sure about?
If I comment out the hook registration at ext_tables.php line 209 OR I set a simple "return" statement at the start of the processData method. Still not able to create new yag galleries.

**Comment by magedeveloper** [comment]
@infabo,

the commit 11f00ca solves the same issue with repositories in the ext_tables.php
Please try your changes then in ExtTablesInclusion.php and it should work.

**Comment by infabo** [comment]
I don't get it. IMHO the "extTablesInclusion-PostProcessing" hook used in this extension has nothing to do with the error (=new records go to pid=0).

**Comment by infabo** [comment]
OK, sry. NVM.
Seems like the simple call in the constructor
https://github.com/magedeveloper/dataviewer/blob/dev-7/Classes/Hooks/ExtTablesInclusion.php#L68

`$this->fieldRepository	= $this->objectManager->get(\MageDeveloper\Dataviewer\Domain\Repository\FieldRepository::class);`

This already breaks the whole thing.
