### ISSUE TITLE
"Record Save Form": Fatal Error on "Create Record"

### ISSUE THREAD

**Issue by infabo** [magedeveloper/dataviewer#15]
TYPO3 7.6.18
dataviewer dev-7

Scenario A: Not logged in to TYPO3 backend. Submit a record in FE via the "Record Save Form", results in error.

The error message:

`Fatal error: Call to a member function substr() on null in /var/www/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php on line 1862`

Even though the error occurs in the core, I would see the source to be in the extension.

https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L1862

Scenario B: Logged in to TYPO3 backend. Submit a record in FE via the "Record Save Form", works fine.

Problem is, that $GLOBALS['LANG'] does not get initialized in Scenario A. I don't know why, it skips the bootstrap somehow (where $GLOBALS['LANG'] would get initialized). Already debugged it via XDebug, but it didn't get me further.

**Comment by magedeveloper** [comment]
Hey @infabo,
that's definately a problem of the DataHandler which i am extending. I will review the whole form plugin soon and see what i can improve.

**Comment by infabo** [comment]
Did go up the callstack and now I may found the problem.

https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L162

That's why the LANG global is available, when logged into backend.

Maybe the solution is to initialize the LanguageService in FormController if not available? Like here: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/frontend/Classes/Utility/EidUtility.php#L61

**Comment by adrienjacob** [comment]
I confirm the issue on dev-8 / Typo3 8.7.1

**Comment by magedeveloper** [comment]
Commits b807624 for dev-7 and afbf247 for dev-8 should solve that issue.

**Comment by adrienjacob** [comment]
Thanks Bastian... I tried it, but I still get this error : 
```
Return value of TYPO3\CMS\Core\Configuration\Richtext::getBackendUser() must be an instance of TYPO3\CMS\Core\Authentication\BackendUserAuthentication, null returned 

TypeError thrown in file
/var/www/typo3/source/typo3_src-8.7.1/typo3/sysext/core/Classes/Configuration/Richtext.php in line 177.

31 TYPO3\CMS\Core\Configuration\Richtext::getBackendUser()

/var/www/typo3/source/typo3_src-8.7.1/typo3/sysext/core/Classes/Configuration/Richtext.php:
00142:     {
00143:         // Override with pageTs if needed
00144:         $backendUser = $this->getBackendUser();
00145:         return $backendUser->getTSConfig('RTE', BackendUtility::getPagesTSconfig($pid));
00146:     }

30 TYPO3\CMS\Core\Configuration\Richtext::getRtePageTsConfigOfPid(0)

/var/www/typo3/source/typo3_src-8.7.1/typo3/sysext/core/Classes/Configuration/Richtext.php:
00066:         // Then overload with RTE.config.tt_content.bodytext
00067:         // Then overload with RTE.config.tt_content.bodytext.types.textmedia
00068:         $fullPageTsConfig = $this->getRtePageTsConfigOfPid($pid);
00069:         $fullPageTsConfig = !empty($fullPageTsConfig['properties']) ? $fullPageTsConfig['properties'] : [];
00070:         $defaultPageTsConfigOverrides = isset($fullPageTsConfig['default.']) ? $fullPageTsConfig['default.'] : null;

29 TYPO3\CMS\Core\Configuration\Richtext::getConfiguration("tx_dataviewer_domain_model_record", "7_rte", 0, "1", array)
```

**Comment by infabo** [comment]
dev-7 OK.

**Comment by magedeveloper** [comment]
Hi,
i added a commit that blank-loads the needed Backend User to get this work and immediately unsets it.

**Comment by adrienjacob** [comment]
Thanks, but now I got another error : 
```
Call to a member function getModuleData() on null 

Error thrown in file
/var/www/typo3/source/typo3_src-8.7.1/typo3/sysext/backend/Classes/Clipboard/Clipboard.php in line 116.

29 TYPO3\CMS\Backend\Clipboard\Clipboard::initializeClipboard()

/var/www/typo3/source/typo3_src-8.7.1/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaGroup.php:
00093:                 $allowed = GeneralUtility::trimExplode(',', $result['processedTca']['columns'][$fieldName]['config']['allowed'], true);
00094:                 $clipboard = GeneralUtility::makeInstance(Clipboard::class);
00095:                 $clipboard->initializeClipboard();
00096:                 $clipboardElements = $clipboard->elFromTable('_FILE');
00097:                 if ($allowed[0] !== '*') {

28 TYPO3\CMS\Backend\Form\FormDataProvider\TcaGroup::addData(array)

/var/www/typo3/source/extensions-test/dataviewer/Classes/Form/Fieldtype/AbstractFieldtype.php:
00275: 
00276:   foreach($this->formDataProviders as $fdp)
00277:    $tca = $fdp->addData($tca);
00278: 
00279:  }

27 MageDeveloper\Dataviewer\Form\Fieldtype\AbstractFieldtype::prepareTca(array)
```

**Comment by adrienjacob** [comment]
Last commit on 7th June fixed this last issue, thanks...
Now I have a slightly different behaviour : I used to display stuff related to the submitted record, but it seems {record} is now empty after the form has been submitted (without page redirection).

**Comment by magedeveloper** [comment]
hi @adrienjacob,
I added a commit that respects the correct controller name on the final redirect when no redirect targets are set in the plugin.

**Comment by adrienjacob** [comment]
Thanks @magedeveloper, working now !
