### ISSUE TITLE
Issues with last commits

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#21]
Dear Bastian,
I tried the last commits from this summer on branch dev-8, and I experience issues. It seems the last one working properly would be the one from July 10th (https://github.com/magedeveloper/dataviewer/commit/b0732663a5a13ca7a2b976a8b5db3de465c810eb). With the one from July 18th (https://github.com/magedeveloper/dataviewer/commit/c585f040df6d27d55263ac45ad4d7574fbc40c51), some display plugins get broken. And with the last one (https://github.com/magedeveloper/dataviewer/commit/e537711517703e9f0f60545bff95bb8f7d5fc10f), several other things get broken. I even have some funny figures displayed (a debug trace with record IDs ?).
So my question is : are there breaking changes requiring some special action during the update process ?
Otherwise I'll probably have to stick with the last version working for me...

**Comment by magedeveloper** [comment]
Hi, these are partial changes that will be fully completed within the next weeks.
