### ISSUE TITLE
Sorting dv:filter.recordsByField viewhelper

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#30]
Dear Bastian,
I've been using the <dv:filter.recordsByField> viewhelper, it seems to lose the current sorting order... Is there any way to keep the current sorting or maybe force it as an additional argument ?
Thanks in advance...
Adrien

**Comment by magedeveloper** [comment]
Closing this, sorting now natively works, also with integrated new viewhelpers.
