### ISSUE TITLE
Typo3 v9 compatibility

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#31]
Hi, this is just the usual question : are there any plans to do a v9 compatible version ? I just tried it and it breaks the back-end... thanks !

**Comment by k3n-bastian** [comment]
Hi Adrien, 
i am preparing a huge rollout of far advanced DataViewer Versions for TYPO3 8 LTS and TYPO3 9 LTS that are currently in development.

**Comment by magedeveloper** [comment]
Hi Adrien,
i am preparing a huge rollout of far advanced DataViewer Versions for TYPO3 8 LTS and TYPO3 9 LTS that are currently in development.
