### ISSUE TITLE
Feature request : image manipulation

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#32]
Would it be possible to include the Typo3 back-end image manipulation (cropping) in image / FAL data fields ? I tried defining a "TCA" type datafield with [this article](https://www.derhansen.de/2017/06/typo3-87-enable-image-cropping-tool-own-extension.html) but didn't manage...
Thanks in advance !

**Comment by magedeveloper** [comment]
Closing this, will be integrated in the upcoming release.
