### ISSUE TITLE
Argument "defaultController" has already been defined

### ISSUE THREAD

**Issue by spacexplorer** [magedeveloper/dataviewer#4]
This is with Typo 8.5 - although compatibility is only stated to be with up to 8.3
I would love to have this working in >8.5 though...

in Backend: DataViewer Tab displays: 
#1253036401: Argument "defaultController" has already been defined, thus it should not be defined again. (More information)

24. TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper::registerArgument("defaultController", "string", "defaultController")

.....
...

20. TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperResolver::getArgumentDefinitionsForViewHelper(MageDeveloper\Dataviewer\ViewHelpers\Backend\ActionMenuViewHelper)

etc....

**Comment by spacexplorer** [comment]
in file:
ext\dataviewer\Classes\Controller\BackendController.php

-----------------------
	protected $defaultContoller = "BackendModuleController";
----------------------
note: no "r"
but:
-----------------------
		return $this->defaultController;
-----------------------

**Comment by spacexplorer** [comment]
could it be conflict with extbase in Typo3 8.5 autoload
---------------------
\typo3conf\ext\dataviewer\Classes\ViewHelpers\Backend\ActionMenuViewHelper.php
---------------------
rename variable 
@param string $defaultController

**Comment by magedeveloper** [comment]
Hey @spacexplorer,
theres some more than this to get compatibility to TYPO3 8.4+.
I will release a fully compatible version, when the TYPO3 8 LTS is released.

Till then, i am occasionally pushing updates to a 8-dev branch, that i am going to add in a few days after the next 1.6.0 appears in the TER.

**Comment by spacexplorer** [comment]
Hi magedeveloper,
thanks
stunning extension
only found it now that I am doing a custom item... 
Yes, I can confirm other issues with fluid
The template not found error locked the backend
until I moved dataviewer out of the ext folder
see:
EXT:form is broken since fluid 2.2.0
https://forge.typo3.org/issues/79439

**Comment by magedeveloper** [comment]
Hey @spacexplorer ,

i added the 8-dev branch to the repository. It is not fully working until i figured out all the small changes that have been made to the Field-Elements in the new version. I also had to accept that i need to create two different versions of the extension: one for 7 LTS and one for 8 LTS so the code can stay clean.

**Comment by adrienjacob** [comment]
Hi @magedeveloper, I just tried the dev-8 branch on typo3 8.7 LTS... I know you've been working on v8 compatibility, but I wanted to make sure you're aware of these issues: 
- Insert record plugin now displays the form in raw html
- In the back-end, when editing / creating a datafield, the field configuration doesn't work anymore

Thanks in advance!

**Comment by spacexplorer** [comment]
I was waiting for 8.7 LTS and would have liked to use dataviewer VS custom extension... I previously created records and on 8.7 clicking on the edit records:
----------------------------------------------------------------------------------------
#1481401892: Field condition "FIELD:datatype:REQ:0" must have "true" or "false" as fourth part. Example: "FIELD:myField:REQ:true (More information)
----------------------------------------------------------------------------------------

I think this plugin could be a huge timesaver for custom content that I want to have as unique hierarchical database entries vs just based on custom content element without having to create a full new extension

But not working on >8.5

Will keenly watch the ongoing development

Thanks

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 9. April 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 10. April 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Ernest Peter (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by adrienjacob** [comment]
Update on the first problem (Insert record plugin now displays the form in raw html) : I could solve it by adding raw formating in /Resources/Private/Templates/Form/Index.html
`<f:format.raw><dataviewer:render.template template="{template}" arguments="{_all}" /></f:format.raw>`
But not sure it's a very satisfying solution. What's strange is that applying the same format ViewHelper in the form template itself doesn't work...

So the form now displays properly, but after testing it doesn't actually save the record (a new record is created, but it's empty).

**Comment by magedeveloper** [comment]
Just to clear that, the second issue is fixed in editing TCA tx_dataviewer_domain_model_record.php and changing REQ:0 to REQ:false

This and other fixes will be implemented in the next 2.0.0 that will be 8+ LTS compatible.
