### ISSUE TITLE
Tab "Display Settings" missing in the "display records" list plugin

### ISSUE THREAD

**Issue by ackerapps** [magedeveloper/dataviewer#5]
Hi

I would like to sort records by date in the "display records" plugin. In your news example you did this. However in my installation the "Display Settings" tab is completely missing. Why is this happening?

My installation: TYPO3 7.6.15, PHP 7.0.11

**Comment by magedeveloper** [comment]
This issue should be fixed in the 1.6.0 version. if you are on this version just let me know and we will see further.

**Comment by ackerapps** [comment]
just updated from 1.5.0 and it's showing up again. Thanks very much 👍
