### ISSUE TITLE
Impossible to set predefined templates

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#7]
I added this line in my template TS but it still won't show the predefined template
`plugin.tx_dataviewer.templates.test = fileadmin/templates/dataviewer/foo/bar.html`
I tested your "playground" environment and it works, but I can't find the difference with my setup... I'll keep searching for a possible mistake on my side, but already spent quite a bit of time on this.

**Comment by magedeveloper** [comment]
Hi Adrien, 
Templates also do not appear in the list when the file is not accessible. Maybe this helps a bit.

**Comment by adrienjacob** [comment]
Strange, I double checked that the files exist, and anyway I also tried with just `plugin.tx_dataviewer.templates.FOO = --div--`
Have you tried with the latest Typo3 version (7.6.15) ?

**Comment by adrienjacob** [comment]
This is fixed with the latest version on branch dev-8...
