### ISSUE TITLE
Search plugin

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#9]
Hi again. I have the following problem with the search plugin (on v. 1.7.2 and 2.00 for Typo3 v8) : while it works ok if I search only the record title, or a single field, I cannot get it to work on several fields. I tried to set the `OR ... ` condition, or others variants `OR (...) ` etc, but it won't work. It seems it always performs an `AND` query.
I wanted to have a look at the SQL query, but couldn't find in the doc how to enable debug output. `plugin.tx_dataviewer.settings.debug = 1` didn't seem to work.

**Comment by magedeveloper** [comment]
hi adrien,

that bug will be fixed in the 1.7.3 (for 7 LTS) and 2.0 (final for 8 LTS)

**Comment by adrienjacob** [comment]
Ok thanks... don't hesitate to push recent changes to the GIT repo, I might have some time to contribute on simple issues.
Also I'd be interested to know how to enable debug output.

**Comment by magedeveloper** [comment]
Debug Output is only configured in the Records Plugin.
